export const locations = [
  "San Francisco",
  "Atherton",
  "Belmont",
  "Brisbane",
  "Burlingame",
  "Colma",
  "Daly City",
  "East Palo Alto",
  "Foster City",
  "Half Moon Bay",
  "Hillsborough",
  "Menlo Park",
  "Millbrae",
  "Pacifica",
  "Portola Valley",
  "Redwood City",
  "San Bruno",
  "San Carlos",
  "San Mateo",
  "South San Francisco",
  "Woodside",
  "Alameda",
  "Albany",
  "Berkeley",
  "Dublin",
  "Emeryville",
  "Fremont",
  "Hayward",
  "Newark",
  "Oakland",
  "Piedmont",
  "San Leandro",
  "Union City",
];
